# Generated by Django 2.1.3 on 2019-01-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_likes',
            field=models.IntegerField(default=0),
        ),
    ]
