# Generated by Django 2.1.3 on 2019-02-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190129_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, only the members of the club can see this post.'),
        ),
    ]
