# Generated by Django 2.1.3 on 2019-01-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_subscribed_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option',
            new_name='option_text',
        ),
    ]
