# Generated by Django 2.1.3 on 2019-01-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_no_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Images larger than 2.2 MBs are not supported. \n You may get a 403 error if you try to upload images that exceed this size', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If unchecked, only the members of the club can see this post.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='notify_followers',
            field=models.BooleanField(default=False, help_text='Check this if you would like to send email to all members/followers about this new post'),
        ),
    ]
