# Generated by Django 2.1.3 on 2019-01-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190108_0042'),
        ('posts', '0002_auto_20190107_2123'),
    ]

    operations = [
    ]
