# Generated by Django 2.1.3 on 2019-01-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190110_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck this if you just want to save as draft and edit later before publishing'),
        ),
    ]
