# Generated by Django 2.1.3 on 2019-01-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_merge_20190108_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinnedpost',
            options={'ordering': ['-post__last_updated']},
        ),
    ]
