# Generated by Django 2.1.3 on 2019-01-21 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190121_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='interested_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
