# Generated by Django 2.1.3 on 2019-01-11 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Make it False when you wish to stop collecting votes'),
        ),
        migrations.AddField(
            model_name='poll',
            name='track_votes',
            field=models.BooleanField(default=True, help_text='If checked, it will be tracked, which user has voted for                                        which option. If unchecked, voting will be anonymous. (In both cases, each user                                         can vote only once)'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Option'),
        ),
    ]
