# Generated by Django 2.1.3 on 2018-12-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20181228_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_creator',
            new_name='author',
        ),
    ]
