# Generated by Django 2.1.3 on 2019-01-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postupdate_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-last_updated']},
        ),
    ]
