# Generated by Django 2.1.3 on 2019-01-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_event'),
        ('posts', '0006_post_liked_users'),
    ]

    operations = [
    ]
