# Generated by Django 2.1.3 on 2019-01-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_postapprover'),
        ('posts', '0007_auto_20190114_2159'),
    ]

    operations = [
    ]
