# Generated by Django 2.1.3 on 2018-12-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='encrypted_id',
            field=models.BigIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
