# Generated by Django 2.1.3 on 2019-01-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('put_calendar', '0003_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
