# Generated by Django 2.1.3 on 2019-01-18 17:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='title',
        ),
        migrations.AddField(
            model_name='calendar',
            name='work_title',
            field=models.CharField(default=' ', max_length=34),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 18, 17, 15, 38, 166874, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
