# Generated by Django 2.1.3 on 2019-01-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleauth',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='googleauth',
            name='google_salt',
        ),
        migrations.RemoveField(
            model_name='googleauth',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='googleauth',
            name='auth_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleauth',
            name='firebase_uid',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='googleauth',
            name='profile_pic_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleauth',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
