# Generated by Django 2.1.3 on 2019-01-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190108_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleauth',
            name='firebase_uid',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
