# Generated by Django 2.1.3 on 2019-01-08 09:39

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190108_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='batch',
            field=models.CharField(blank=True, choices=[('UG1', 'UG1'), ('UG2', 'UG2'), ('UG3', 'UG3'), ('UG4', 'UG4')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following_clubs',
            field=models.ManyToManyField(blank=True, to='base.Club'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[registration.models.phone_number_validator], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
