# Generated by Django 2.1.3 on 2019-01-16 19:35

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='about',
            field=models.TextField(blank=True, help_text='Say a few lines about your club', null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.club_logo_upload),
        ),
    ]
