# Generated by Django 2.1.3 on 2019-01-19 03:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clubmentor',
            unique_together={('user', 'club')},
        ),
    ]
