# Generated by Django 2.0.6 on 2019-01-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clubadmin',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='clubadmin',
            name='club',
        ),
        migrations.RemoveField(
            model_name='clubadmin',
            name='user',
        ),
        migrations.AlterField(
            model_name='clubpresident',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Club'),
        ),
        migrations.DeleteModel(
            name='ClubAdmin',
        ),
    ]
