# Generated by Django 2.1.3 on 2019-01-14 18:46

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190111_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(db_index=True, max_length=100, validators=[base.models.club_name_validator]),
        ),
    ]
