# Generated by Django 2.1.3 on 2019-01-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_club_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='about',
            field=models.TextField(blank=True, help_text='Say a few lines about your club', max_length=500, null=True),
        ),
    ]
