# Generated by Django 2.1.3 on 2019-01-19 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190119_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='club',
            old_name='logo',
            new_name='back_img',
        ),
        migrations.AddField(
            model_name='clubsettings',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Club'),
        ),
    ]
