# Generated by Django 2.1.3 on 2019-01-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190119_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='num_users',
        ),
    ]
