# Generated by Django 2.1.3 on 2019-01-21 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190121_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Club'),
        ),
    ]
