# Generated by Django 2.1.3 on 2019-01-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
