# Generated by Django 2.1.3 on 2019-01-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190125_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, help_text='Give the full url', null=True),
        ),
    ]
